const productCategory = [
    { id: 41, label: "Abs", value: "abs" },
    { id: 43, label: "Belt Drive", value: "bdrive" },
    { id: 42, label: "Bearing Kit", value: "bkit" },
    { id: 39, label: "BSVI Products", value: "bsvi" },
    { id: 25, label: "Brake Switch", value: "brakeswitch" },
    { id: 6, label: "CDEI", value: "cdei" },
    { id: 2, label: "C.D.I", value: "cdi" },
    { id: 12, label: "Consumable Filters", value: "cfilters" },
    { id: 36, label: "Drum / Drum Plate / Coupling Hub / Wheel Rim", value: "drum" },
    { id: 32, label: "Electronic Relay", value: "erelay" },
    { id: 11, label: "Filters", value: "filters" },
    { id: 13, label: "Filters & Horn", value: "fhorn" },
    { id: 38, label: "Other Products (Cylinder Kit / Fuse Blade)", value: "fblade" },
    { id: 23, label: "Floor Set / Speedo Gear", value: "fspeedogear" },
    { id: 27, label: "Fuel Caps", value: "fcaps" },
    { id: 28, label: "Fuel Cock", value: "fuelcock" },
    { id: 14, label: "Fuel Pump Strainer", value: "pump" },
    { id: 35, label: "Lever & Yoke", value: "lever" },
    { id: 30, label: "Varroc Oil / Grease", value: "grease" },
    { id: 17, label: "Handle Bar", value: "handlebar" },
    { id: 3, label: "Handle Bar Switch", value: "handle" },
    { id: 22, label: "Handle Bar Weigth", value: "barweigth" },
    { id: 15, label: "Horn", value: "horn" },
    { id: 9, label: "Ignition Coil", value: "icoil" },
    { id: 7, label: "ICDI / CDI", value: "icdi" },
    { id: 21, label: "Insulator For Carburetor", value: "insulator" },
    { id: 31, label: "Lighting Products", value: "lproducts" },
    { id: 10, label: "Magneto Assembly & Spares", value: "magneto" },
    { id: 4, label: "Modular Switch", value: "modular" },
    { id: 40, label: "Oring", value: "oring" },
    { id: 18, label: "Other (Oil Pump Gear / Clutch Roller / Plug Cap)", value: "other" },
    { id: 29, label: "Gaskets", value: "gaskets" },
    { id: 19, label: "Rear View Mirror", value: "rvm" },
    { id: 8, label: "Regulator Rectifier (R.R.)", value: "rr" },
    { id: 26, label: "Switches / Locks", value: "slocks" },
    { id: 1, label: "Starter Moter & Spares", value: "starter" },
    { id: 24, label: "Speedo Gear", value: "speedogear" },
    { id: 44, label: "TPSR / Swing Arm Assly", value: "tpsr" },
    { id: 37, label: "Footrest Bracket", value: "footrest" },
    { id: 33, label: "Relay", value: "relay" },
    { id: 34, label: "Flasher / Buzzer", value: "flasher" },
    { id: 20, label: "Rubber Items", value: "horn" },
    { id: 16, label: "Oil Seal Kit", value: "oilkit" }
  ];
  
  export default productCategory.sort((a, b) => a.label.localeCompare(b.label));
  